### PR TITLE
ci(release): fix issue with protected branch

### LINKED ISSUE #34: Fix Publish Action
Publish to NPM Action fails with 

```
command: 'git push --tags https://x-access-token:[secure]@github.com/arianacosta/poetic.git HEAD:master',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'remote: error: GH006: Protected branch update failed for refs/heads/master.        \n' +
    'remote: error: At least 1 approving review is required by reviewers with write access.        \n' +
    'To https://github.com/arianacosta/poetic.git\n' +
    ' ! [remote rejected] HEAD -> master (protected branch hook declined)\n' +
    "error: failed to push some refs to 'https://x-access-token:[secure]@github.com/arianacosta/poetic.git'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: '@semantic-release/git'
}
```

How can we have automatic semantic releases while enforcing code reviews?

### PR DESCRIPTION
**Pull request by oleg-koval**
This PR should be merged after actions in #34 are performed

closes #34

### CODE REVIEW

**Review by arianacosta — APPROVED** [review]
Perfect. I've created the token. Merging to test if this works. Thank you!

**Comment by arianacosta** [comment]
@oleg-koval I just noticed the `do-not-merge` label... Anyhow, I tested it out, and it seems to be working great. Thank you so much for your help!

In your opinion, what other future improvements (apart from testing) do you think we can have for the CI pipeline?

**Comment by oleg-koval** [comment]
@arianacosta I would say it's necessary to have linting, formating and spellcheck in place. Also tests if it's possible. WDYT?

**Comment by oleg-koval** [comment]
@arianacosta also auto update dependency thingy

**Comment by arianacosta** [comment]
@oleg-koval I totally agree. Linting and unit tests for the repo are coming soon, I'm working on that. I was also thinking that `commitlint` would be useful in conjunction with `commitizen` for the `semantic-release`. I'll add an issue for that in case you are interested. About the dependency update script,  that's no longer necessary, because I changed the installation strategy.

Thanks!

**Pull request merged**
